# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jing Zhang

email: zhang_jing16@fudan.edu.cn

#description: > Mingzhang's homepage# this means to ignore newlines until "baseurl:"

baseurl: "/" # the subpath of your site, e.g. /blog

url: "https://jingzhang1.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Social media usernames
github_username:      16211020010@fudan.edu.cn
#stackexchange_username: 5834317
#stackoverflow_username: 6307081
#twitter_username:     HeesooRandi
#facebook_username:    rgriff23
#linkedin_username:    randigriffin
#gplus_username: 112245393392023660495

#maruku 
markdown: kramdown

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  
  
  
